services:
  tailcam:
    image: bradmartin333/tailcam:latest
    container_name: tailcam
    ports:
      - "8555:8080"
    # Add a line per camera; mapping a device that doesn't exist stops the container from starting.
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
